name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: pcov

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: install
        run: |
          composer install --no-progress --no-interaction --ansi
      - name: cgl
        run: |
          composer t3g:cgl
      - name: phpstan
        run: |
          composer t3g:phpstan
      - name: unit test
        run: |
          composer t3g:test:unit
      - name: functional test
        run: |
          composer t3g:test:functional
      - name: rector
        run: |
          composer t3g:rector:dry-run
